package com.future.bbetter.member.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Friends.java auto generated by Charles. 2017/9/3 下午 05:39:31
 */
@Entity
@Table(name = "friend")
public class Friend {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "friend_id")
	private Long friendId;
	@Column(name = "member_id")
	private Long memberId;
	@Column(name = "friend_member_id")
	private Long friendMemberId;
	@Column(name = "source")
	private Integer source;
	@Column(name = "is_accept")
	private Integer isAccept;
	@Column(name = "is_blockade")
	private Integer isBlockade;
	@Column(name = "createdate")
	private Date createdate;

	public Friend(){}

	public Long getFriendId() {
		return friendId;
	}

	public void setFriendId(Long friendId) {
		this.friendId = friendId;
	}

	public Long getMemberId() {
		return memberId;
	}

	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}

	public Long getFriendMemberId() {
		return friendMemberId;
	}

	public void setFriendMemberId(Long friendMemberId) {
		this.friendMemberId = friendMemberId;
	}

	public Integer getSource() {
		return source;
	}

	public void setSource(Integer source) {
		this.source = source;
	}

	public Integer getIsAccept() {
		return isAccept;
	}

	public void setIsAccept(Integer isAccept) {
		this.isAccept = isAccept;
	}

	public Integer getIsBlockade() {
		return isBlockade;
	}

	public void setIsBlockade(Integer isBlockade) {
		this.isBlockade = isBlockade;
	}

	public Date getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Override
	public String toString() {
		return "Friend [friendId=" + friendId + ", memberId=" + memberId + ", friendMemberId=" + friendMemberId
				+ ", source=" + source + ", isAccept=" + isAccept + ", isBlockade=" + isBlockade + ", createdate="
				+ createdate + "]";
	}

	
	
}
