package com.future.bbetter.member.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Friends.java auto generated by Charles. 2017/9/3 下午 05:39:31
 */
@IdClass(value=FriendsPK.class)
@Entity
@Table(name = "friends")
public class Friends {

	@Id
	@Column(name = "member_id")
	private Long memberId;
	@Id
	@Column(name = "friend_member_id")
	private Long friendMemberId;
	@Column(name = "source")
	private Integer source;
	@Column(name = "is_accept")
	private String isAccept;
	@Column(name = "is_blockade")
	private String isBlockade;
	@Column(name = "createdate")
	private Date createdate;

	public Friends(){}

	public void setMemberId(Long memberId){
		this.memberId = memberId;
	}
	public Long getMemberId() {
			return this.memberId;
	}
	public void setFriendMemberId(Long friendMemberId){
		this.friendMemberId = friendMemberId;
	}
	public Long getFriendMemberId() {
			return this.friendMemberId;
	}
	public void setSource(Integer source){
		this.source = source;
	}
	public Integer getSource() {
			return this.source;
	}
	public void setIsAccept(String isAccept){
		this.isAccept = isAccept;
	}
	public String getIsAccept() {
			return this.isAccept;
	}
	public void setIsBlockade(String isBlockade){
		this.isBlockade = isBlockade;
	}
	public String getIsBlockade() {
			return this.isBlockade;
	}
	public void setCreatedate(Date createdate){
		this.createdate = createdate;
	}
	public Date getCreatedate() {
			return this.createdate;
	}


	@Override
	public String toString() {
		return String.format(
				"Friends [memberId=%s, friendMemberId=%s, source=%s, isAccept=%s, isBlockade=%s, createdate=%s]",memberId, friendMemberId, source, isAccept, isBlockade, createdate);
	}
}
