package com.future.bbetter.member.model;
// Generated 2017/10/14 上午 11:25:08 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Friend generated by hbm2java
 */
@Entity
@Table(name = "friend", catalog = "bbetter")
public class Friend implements java.io.Serializable {

	private Long friendId;
	private Member memberByFriendMemberId;
	private Member memberByMemberId;
	private Integer source;
	private int isAccept;
	private int isBlockade;
	private Date createdate;
	private Date updatedate;

	public Friend() {
	}

	public Friend(Member memberByFriendMemberId, Member memberByMemberId, int isAccept, int isBlockade,
			Date createdate) {
		this.memberByFriendMemberId = memberByFriendMemberId;
		this.memberByMemberId = memberByMemberId;
		this.isAccept = isAccept;
		this.isBlockade = isBlockade;
		this.createdate = createdate;
	}

	public Friend(Member memberByFriendMemberId, Member memberByMemberId, Integer source, int isAccept, int isBlockade,
			Date createdate, Date updatedate) {
		this.memberByFriendMemberId = memberByFriendMemberId;
		this.memberByMemberId = memberByMemberId;
		this.source = source;
		this.isAccept = isAccept;
		this.isBlockade = isBlockade;
		this.createdate = createdate;
		this.updatedate = updatedate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "friend_id", unique = true, nullable = false)
	public Long getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Long friendId) {
		this.friendId = friendId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "friend_member_id", nullable = false)
	public Member getMemberByFriendMemberId() {
		return this.memberByFriendMemberId;
	}

	public void setMemberByFriendMemberId(Member memberByFriendMemberId) {
		this.memberByFriendMemberId = memberByFriendMemberId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getMemberByMemberId() {
		return this.memberByMemberId;
	}

	public void setMemberByMemberId(Member memberByMemberId) {
		this.memberByMemberId = memberByMemberId;
	}

	@Column(name = "source")
	public Integer getSource() {
		return this.source;
	}

	public void setSource(Integer source) {
		this.source = source;
	}

	@Column(name = "is_accept", nullable = false)
	public int getIsAccept() {
		return this.isAccept;
	}

	public void setIsAccept(int isAccept) {
		this.isAccept = isAccept;
	}

	@Column(name = "is_blockade", nullable = false)
	public int getIsBlockade() {
		return this.isBlockade;
	}

	public void setIsBlockade(int isBlockade) {
		this.isBlockade = isBlockade;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedate", length = 19)
	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

}
