package com.future.bbetter.member.model;
// Generated 2017/10/14 上午 11:25:08 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.ColumnDefault;

import com.future.bbetter.achievement.model.AchievementHad;
import com.future.bbetter.pet.model.PetsHad;
import com.future.bbetter.schedule.model.ScheduleOwner;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "member", catalog = "bbetter", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Member implements java.io.Serializable {

	private Long memberId;
	private String email;
	private String password;
	private String salt;
	private String name;
	private int gender;
	private BigDecimal money;
	private Date birthday;
	private String address;
	private Date createdate;
	private Date updatedate;
	private String imageUrl;
	private Set<AchievementHad> achievementHads = new HashSet<AchievementHad>(0);
	private Set<Friend> friendsForFriendMemberId = new HashSet<Friend>(0);
	private Set<Friend> friendsForMemberId = new HashSet<Friend>(0);
	private Set<PetsHad> petsHads = new HashSet<PetsHad>(0);

	public Member() {
	}

	public Member(String email, String password, String name, int gender, BigDecimal money, String address, String imageUrl) {
		this.email = email;
		this.password = password;
		this.name = name;
		this.gender = gender;
		this.money = money;
		this.address = address;
		this.imageUrl = imageUrl;
	}

	public Member(String email, String password, String salt, String name, int gender, BigDecimal money, Date birthday,
			String address, String imageUrl, Date createdate, Date updatedate, Set<AchievementHad> achievementHads,
			Set<Friend> friendsForFriendMemberId, Set<ScheduleOwner> scheduleOwners, Set<Friend> friendsForMemberId,
			Set<PetsHad> petsHads) {
		this.email = email;
		this.password = password;
		this.salt = salt;
		this.name = name;
		this.gender = gender;
		this.money = money;
		this.birthday = birthday;
		this.address = address;
		this.imageUrl = imageUrl;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.achievementHads = achievementHads;
		this.friendsForFriendMemberId = friendsForFriendMemberId;
		this.friendsForMemberId = friendsForMemberId;
		this.petsHads = petsHads;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "member_id", unique = true, nullable = false)
	public Long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}

	@Column(name = "email", unique = true, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 60)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "salt", length = 45)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "gender", nullable = false)
	public int getGender() {
		return this.gender;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}
	
	@Column(name = "image_url", length = 100)
	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "money", nullable = false, precision = 10)
	@ColumnDefault(value = "0.0")
	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "birthday", length = 19)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedate", length = 19)
	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<AchievementHad> getAchievementHads() {
		return this.achievementHads;
	}

	public void setAchievementHads(Set<AchievementHad> achievementHads) {
		this.achievementHads = achievementHads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memberByFriendMemberId")
	public Set<Friend> getFriendsForFriendMemberId() {
		return this.friendsForFriendMemberId;
	}

	public void setFriendsForFriendMemberId(Set<Friend> friendsForFriendMemberId) {
		this.friendsForFriendMemberId = friendsForFriendMemberId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memberByMemberId")
	public Set<Friend> getFriendsForMemberId() {
		return this.friendsForMemberId;
	}

	public void setFriendsForMemberId(Set<Friend> friendsForMemberId) {
		this.friendsForMemberId = friendsForMemberId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<PetsHad> getPetsHads() {
		return this.petsHads;
	}

	public void setPetsHads(Set<PetsHad> petsHads) {
		this.petsHads = petsHads;
	}

}
