package com.future.bbetter.member.model;
// Generated 2017/11/1 下午 03:50:06 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ThirdPartAuth generated by hbm2java
 */
@Entity
@Table(name = "third_part_auth", catalog = "bbetter")
public class ThirdPartAuth implements java.io.Serializable {

	private Long thirdPartAuthId;
	private Long memberId;
	private String providerId;
	private Integer source;

	public ThirdPartAuth() {
	}

	public ThirdPartAuth(Long memberId, String providerId, Integer source) {
		this.memberId = memberId;
		this.providerId = providerId;
		this.source = source;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "third_part_auth_id", unique = true, nullable = false)
	public Long getThirdPartAuthId() {
		return this.thirdPartAuthId;
	}

	public void setThirdPartAuthId(Long thirdPartAuthId) {
		this.thirdPartAuthId = thirdPartAuthId;
	}

	@Column(name = "member_id")
	public Long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}

	@Column(name = "provider_id")
	public String getProviderId() {
		return this.providerId;
	}

	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	@Column(name = "source")
	public Integer getSource() {
		return this.source;
	}

	public void setSource(Integer source) {
		this.source = source;
	}

}
