package com.future.bbetter.schedule.model;
// Generated 2017/10/14 上午 11:25:08 by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScheduleType generated by hbm2java
 */
@Entity
@Table(name = "schedule_type", catalog = "bbetter")
public class ScheduleType implements java.io.Serializable {

	private Integer scheduleTypeId;
	private String name;
	private Date createdate;
	private Set<Schedule> schedule = new HashSet<Schedule>(0);

	public ScheduleType() {
	}
	
	public ScheduleType(Integer scheduleTypeId) {
		this.scheduleTypeId = scheduleTypeId;
	}
	
	public ScheduleType(String name) {
		this.name = name;
	}

	public ScheduleType(String name, Date createdate, Set<Schedule> schedule) {
		this.name = name;
		this.createdate = createdate;
		this.schedule = schedule;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "schedule_type_id", unique = true, nullable = false)
	public Integer getScheduleTypeId() {
		return this.scheduleTypeId;
	}

	public void setScheduleTypeId(Integer scheduleTypeId) {
		this.scheduleTypeId = scheduleTypeId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduleType")
	public Set<Schedule> getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Set<Schedule> schedule) {
		this.schedule = schedule;
	}

}
