package com.future.bbetter.schedule.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ScheduleSubType.java auto generated by Charles. 2017/9/3 下午 05:39:31
 */
@Entity
@Table(name = "schedule_sub_type")
public class ScheduleSubType {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	@Column(name = "schedule_sub_type_id")
	private Integer scheduleSubTypeId;
	@Column(name = "schedule_type_id")
	private Integer scheduleTypeId;
	@Column(name = "name")
	private String name;

	public ScheduleSubType(){}
	public ScheduleSubType(Integer scheduleSubTypeId){
		this.scheduleSubTypeId = scheduleSubTypeId;
	}

	public void setScheduleSubTypeId(Integer scheduleSubTypeId){
		this.scheduleSubTypeId = scheduleSubTypeId;
	}
	public Integer getScheduleSubTypeId() {
			return this.scheduleSubTypeId;
	}
	public void setScheduleTypeId(Integer scheduleTypeId){
		this.scheduleTypeId = scheduleTypeId;
	}
	public Integer getScheduleTypeId() {
			return this.scheduleTypeId;
	}
	public void setName(String name){
		this.name = name;
	}
	public String getName() {
			return this.name;
	}


	@Override
	public String toString() {
		return String.format(
				"ScheduleSubType [scheduleSubTypeId=%s, scheduleTypeId=%s, name=%s]",scheduleSubTypeId, scheduleTypeId, name);
	}
}
