package com.future.bbetter.schedule.model;
// Generated 2017/9/24 下午 02:49:40 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.future.bbetter.member.model.Member;

/**
 * ScheduleHad generated by hbm2java
 */
@Entity
@Table(name = "schedule_had", catalog = "bbetter")
public class ScheduleHad implements java.io.Serializable {

	private Long scheduleHadId;
	private Member member;
	private Schedule schedule;
	private int authority;
	private int isValid;
	private int accumulatedTime;
	private Set<ScheduleRemind> scheduleReminds = new HashSet<ScheduleRemind>(0);

	public ScheduleHad() {
	}

	public ScheduleHad(Member member, Schedule schedule, int authority, int isValid, int accumulatedTime) {
		this.member = member;
		this.schedule = schedule;
		this.authority = authority;
		this.isValid = isValid;
		this.accumulatedTime = accumulatedTime;
	}

	public ScheduleHad(Member member, Schedule schedule, int authority, int isValid, int accumulatedTime,
			Set<ScheduleRemind> scheduleReminds) {
		this.member = member;
		this.schedule = schedule;
		this.authority = authority;
		this.isValid = isValid;
		this.accumulatedTime = accumulatedTime;
		this.scheduleReminds = scheduleReminds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "schedule_had_id", unique = true, nullable = false)
	public Long getScheduleHadId() {
		return this.scheduleHadId;
	}

	public void setScheduleHadId(Long scheduleHadId) {
		this.scheduleHadId = scheduleHadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schedule_id", nullable = false)
	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	@Column(name = "authority", nullable = false)
	public int getAuthority() {
		return this.authority;
	}

	public void setAuthority(int authority) {
		this.authority = authority;
	}

	@Column(name = "is_valid", nullable = false)
	public int getIsValid() {
		return this.isValid;
	}

	public void setIsValid(int isValid) {
		this.isValid = isValid;
	}

	@Column(name = "accumulated_time", nullable = false)
	public int getAccumulatedTime() {
		return this.accumulatedTime;
	}

	public void setAccumulatedTime(int accumulatedTime) {
		this.accumulatedTime = accumulatedTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduleHad")
	public Set<ScheduleRemind> getScheduleReminds() {
		return this.scheduleReminds;
	}

	public void setScheduleReminds(Set<ScheduleRemind> scheduleReminds) {
		this.scheduleReminds = scheduleReminds;
	}

}
