package com.future.bbetter.schedule.model;
// Generated 2017/9/24 下午 02:49:40 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ScheduleType generated by hbm2java
 */
@Entity
@Table(name = "schedule_type", catalog = "bbetter")
public class ScheduleType implements java.io.Serializable {

	private Integer scheduleTypeId;
	private String name;
	private Set<ScheduleSubType> scheduleSubTypes = new HashSet<ScheduleSubType>(0);

	public ScheduleType() {
	}

	public ScheduleType(String name) {
		this.name = name;
	}

	public ScheduleType(String name, Set<ScheduleSubType> scheduleSubTypes) {
		this.name = name;
		this.scheduleSubTypes = scheduleSubTypes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "schedule_type_id", unique = true, nullable = false)
	public Integer getScheduleTypeId() {
		return this.scheduleTypeId;
	}

	public void setScheduleTypeId(Integer scheduleTypeId) {
		this.scheduleTypeId = scheduleTypeId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduleType")
	public Set<ScheduleSubType> getScheduleSubTypes() {
		return this.scheduleSubTypes;
	}

	public void setScheduleSubTypes(Set<ScheduleSubType> scheduleSubTypes) {
		this.scheduleSubTypes = scheduleSubTypes;
	}

}
