package com.future.bbetter.schedule.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ScheduleType.java auto generated by Charles. 2017/9/3 下午 05:39:31
 */
@Entity
@Table(name = "schedule_type")
public class ScheduleType {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	@Column(name = "schedule_type_id")
	private Integer scheduleTypeId;
	@Column(name = "name")
	private String name;

	public ScheduleType(){}
	public ScheduleType(Integer scheduleTypeId){
		this.scheduleTypeId = scheduleTypeId;
	}

	public void setScheduleTypeId(Integer scheduleTypeId){
		this.scheduleTypeId = scheduleTypeId;
	}
	public Integer getScheduleTypeId() {
			return this.scheduleTypeId;
	}
	public void setName(String name){
		this.name = name;
	}
	public String getName() {
			return this.name;
	}


	@Override
	public String toString() {
		return String.format(
				"ScheduleType [scheduleTypeId=%s, name=%s]",scheduleTypeId, name);
	}
}
