package com.future.bbetter.schedule.model;
// Generated 2017/10/14 上午 11:25:08 by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.ColumnDefault;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "schedule", catalog = "bbetter")
public class Schedule implements java.io.Serializable {

	private Long scheduleId;
	private ScheduleType scheduleType;
	private Integer skillId;
	private Date startTime;
	private Date endTime;
	private String name;
	private String location;
	private Integer status;
	private Integer continuousTime;
	private Integer visibility;
	private Integer isCycle;
	private Integer isNeedRemind;
	private Integer isTeamSchedule;
	private Integer isValid;
	private Date createdate;
	private Date updatedate;
	private Set<ScheduleReport> scheduleReports = new HashSet<ScheduleReport>(0);
	private Set<ScheduleHad> scheduleHads = new HashSet<ScheduleHad>(0);
	private Set<CycleRule> cycleRules = new HashSet<CycleRule>(0);

	public Schedule() {
	}
	
	public Schedule(Long scheduleId) {
		this.scheduleId = scheduleId;
	}
	
	public Schedule(ScheduleType scheduleSubType, Date startTime, String name, Integer status, Integer visibility,
			Integer isCycle, Integer isNeedRemind, Integer isTeamSchedule, Integer isValid, Date createdate) {
		this.scheduleType = scheduleSubType;
		this.startTime = startTime;
		this.name = name;
		this.status = status;
		this.visibility = visibility;
		this.isCycle = isCycle;
		this.isNeedRemind = isNeedRemind;
		this.isTeamSchedule = isTeamSchedule;
		this.isValid = isValid;
		this.createdate = createdate;
	}

	public Schedule(ScheduleType scheduleSubType, Date startTime, Date endTime, String name, String location,
			Integer status, Integer continuousTime, Integer visibility, Integer isCycle, Integer isNeedRemind, Integer isTeamSchedule,
			Integer isValid, Date createdate, Date updatedate, Set<ScheduleReport> scheduleReports,
			Set<ScheduleHad> scheduleHads, Set<CycleRule> cycleRules) {
		this.scheduleType = scheduleSubType;
		this.startTime = startTime;
		this.endTime = endTime;
		this.name = name;
		this.location = location;
		this.status = status;
		this.continuousTime = continuousTime;
		this.visibility = visibility;
		this.isCycle = isCycle;
		this.isNeedRemind = isNeedRemind;
		this.isTeamSchedule = isTeamSchedule;
		this.isValid = isValid;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.scheduleReports = scheduleReports;
		this.scheduleHads = scheduleHads;
		this.cycleRules = cycleRules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "schedule_id", unique = true, nullable = false)
	public Long getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Long scheduleId) {
		this.scheduleId = scheduleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schedule_type_id", nullable = false)
	public ScheduleType getScheduleType() {
		return this.scheduleType;
	}

	public void setScheduleType(ScheduleType scheduleType) {
		this.scheduleType = scheduleType;
	}
	
	@Column(name = "skill_id")
	public Integer getSkillId() {
		return skillId;
	}

	public void setSkillId(Integer skillId) {
		this.skillId = skillId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", nullable = false, length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "location", length = 100)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "status", nullable = false)
	@ColumnDefault("1")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "continuous_time")
	public Integer getContinuousTime() {
		return this.continuousTime;
	}

	public void setContinuousTime(Integer continuousTime) {
		this.continuousTime = continuousTime;
	}

	@Column(name = "visibility", nullable = false)
	@ColumnDefault("2")
	public Integer getVisibility() {
		return this.visibility;
	}

	public void setVisibility(Integer visibility) {
		this.visibility = visibility;
	}

	@Column(name = "is_cycle", nullable = false)
	@ColumnDefault("0")
	public Integer getIsCycle() {
		return this.isCycle;
	}

	public void setIsCycle(Integer isCycle) {
		this.isCycle = isCycle;
	}

	@Column(name = "is_need_remind", nullable = false)
	@ColumnDefault("0")
	public Integer getIsNeedRemind() {
		return this.isNeedRemind;
	}

	public void setIsNeedRemind(Integer isNeedRemind) {
		this.isNeedRemind = isNeedRemind;
	}

	@Column(name = "is_team_schedule", nullable = false)
	@ColumnDefault("0")
	public Integer getIsTeamSchedule() {
		return this.isTeamSchedule;
	}

	public void setIsTeamSchedule(Integer isTeamSchedule) {
		this.isTeamSchedule = isTeamSchedule;
	}

	@Column(name = "is_valid", nullable = false)
	@ColumnDefault("1")
	public Integer getIsValid() {
		return this.isValid;
	}

	public void setIsValid(Integer isValid) {
		this.isValid = isValid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedate", length = 19)
	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
	public Set<ScheduleReport> getScheduleReports() {
		return this.scheduleReports;
	}

	public void setScheduleReports(Set<ScheduleReport> scheduleReports) {
		this.scheduleReports = scheduleReports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
	public Set<ScheduleHad> getScheduleHads() {
		return this.scheduleHads;
	}

	public void setScheduleHads(Set<ScheduleHad> scheduleHads) {
		this.scheduleHads = scheduleHads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
	public Set<CycleRule> getCycleRules() {
		return this.cycleRules;
	}

	public void setCycleRules(Set<CycleRule> cycleRules) {
		this.cycleRules = cycleRules;
	}
}
