package com.future.bbetter.schedule.model;
// Generated 2017/10/14 上午 11:25:08 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScheduleHad generated by hbm2java
 */
@Entity
@Table(name = "schedule_had", catalog = "bbetter")
public class ScheduleHad implements java.io.Serializable {

	private Long scheduleHadId;
	private Schedule schedule;
	private ScheduleOwner scheduleOwner;
	private int authority;
	private int isValid;
	private int accumulatedTime;
	private Date createdate;
	private Date updatedate;
	private Set<ScheduleHistory> scheduleHistories = new HashSet<ScheduleHistory>(0);
	private Set<CycleRule> cycleRules = new HashSet<CycleRule>(0);
	private Set<ScheduleRemind> scheduleReminds = new HashSet<ScheduleRemind>(0);

	public ScheduleHad() {
	}

	public ScheduleHad(Schedule schedule, ScheduleOwner scheduleOwner, int authority, int isValid, int accumulatedTime,
			Date createdate) {
		this.schedule = schedule;
		this.scheduleOwner = scheduleOwner;
		this.authority = authority;
		this.isValid = isValid;
		this.accumulatedTime = accumulatedTime;
		this.createdate = createdate;
	}

	public ScheduleHad(Schedule schedule, ScheduleOwner scheduleOwner, int authority, int isValid, int accumulatedTime,
			Date createdate, Date updatedate, Set<ScheduleHistory> scheduleHistories, Set<CycleRule> cycleRules,
			Set<ScheduleRemind> scheduleReminds) {
		this.schedule = schedule;
		this.scheduleOwner = scheduleOwner;
		this.authority = authority;
		this.isValid = isValid;
		this.accumulatedTime = accumulatedTime;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.scheduleHistories = scheduleHistories;
		this.cycleRules = cycleRules;
		this.scheduleReminds = scheduleReminds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "schedule_had_id", unique = true, nullable = false)
	public Long getScheduleHadId() {
		return this.scheduleHadId;
	}

	public void setScheduleHadId(Long scheduleHadId) {
		this.scheduleHadId = scheduleHadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schedule_id", nullable = false)
	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schedule_owner_id", nullable = false)
	public ScheduleOwner getScheduleOwner() {
		return this.scheduleOwner;
	}

	public void setScheduleOwner(ScheduleOwner scheduleOwner) {
		this.scheduleOwner = scheduleOwner;
	}

	@Column(name = "authority", nullable = false)
	public int getAuthority() {
		return this.authority;
	}

	public void setAuthority(int authority) {
		this.authority = authority;
	}

	@Column(name = "is_valid", nullable = false)
	public int getIsValid() {
		return this.isValid;
	}

	public void setIsValid(int isValid) {
		this.isValid = isValid;
	}

	@Column(name = "accumulated_time", nullable = false)
	public int getAccumulatedTime() {
		return this.accumulatedTime;
	}

	public void setAccumulatedTime(int accumulatedTime) {
		this.accumulatedTime = accumulatedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedate", length = 19)
	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduleHad")
	public Set<ScheduleHistory> getScheduleHistories() {
		return this.scheduleHistories;
	}

	public void setScheduleHistories(Set<ScheduleHistory> scheduleHistories) {
		this.scheduleHistories = scheduleHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduleHad")
	public Set<CycleRule> getCycleRules() {
		return this.cycleRules;
	}

	public void setCycleRules(Set<CycleRule> cycleRules) {
		this.cycleRules = cycleRules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduleHad")
	public Set<ScheduleRemind> getScheduleReminds() {
		return this.scheduleReminds;
	}

	public void setScheduleReminds(Set<ScheduleRemind> scheduleReminds) {
		this.scheduleReminds = scheduleReminds;
	}

}
