package com.future.bbetter.schedule.model;
// Generated 2017/10/14 上午 11:25:08 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.ColumnDefault;

/**
 * ScheduleReport generated by hbm2java
 */
@Entity
@Table(name = "schedule_report", catalog = "bbetter")
public class ScheduleReport implements java.io.Serializable {

	private Long scheduleReportId;
	private Schedule schedule;
	private ScheduleOwner scheduleOwner;
	private Date createdate;
	private int isReview;
	private int reportType;

	public ScheduleReport() {
	}

	public ScheduleReport(Schedule schedule, ScheduleOwner scheduleOwner, Date createdate, int isReview,
			int reportType) {
		this.schedule = schedule;
		this.scheduleOwner = scheduleOwner;
		this.createdate = createdate;
		this.isReview = isReview;
		this.reportType = reportType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "schedule_report_id", unique = true, nullable = false)
	public Long getScheduleReportId() {
		return this.scheduleReportId;
	}

	public void setScheduleReportId(Long scheduleReportId) {
		this.scheduleReportId = scheduleReportId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schedule_schedule_id", nullable = false)
	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schedule_owner_id", nullable = false)
	public ScheduleOwner getScheduleOwner() {
		return this.scheduleOwner;
	}

	public void setScheduleOwner(ScheduleOwner scheduleOwner) {
		this.scheduleOwner = scheduleOwner;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "is_review", nullable = false)
	@ColumnDefault("0")
	public int getIsReview() {
		return this.isReview;
	}

	public void setIsReview(int isReview) {
		this.isReview = isReview;
	}

	@Column(name = "report_type", nullable = false)
	public int getReportType() {
		return this.reportType;
	}

	public void setReportType(int reportType) {
		this.reportType = reportType;
	}

}
