package com.future.bbetter.schedule.model;
// Generated 2017/10/14 上午 11:25:08 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScheduleHistory generated by hbm2java
 */
@Entity
@Table(name = "schedule_history", catalog = "bbetter")
public class ScheduleHistory implements java.io.Serializable {

	private Long scheduleHistoryId;
	private ScheduleHad scheduleHad;
	private int status;
	private Date createdate;

	public ScheduleHistory() {
	}

	public ScheduleHistory(ScheduleHad scheduleHad, int status, Date createdate) {
		this.scheduleHad = scheduleHad;
		this.status = status;
		this.createdate = createdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "schedule_history_id", unique = true, nullable = false)
	public Long getScheduleHistoryId() {
		return this.scheduleHistoryId;
	}

	public void setScheduleHistoryId(Long scheduleHistoryId) {
		this.scheduleHistoryId = scheduleHistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schedule_had_id", nullable = false)
	public ScheduleHad getScheduleHad() {
		return this.scheduleHad;
	}

	public void setScheduleHad(ScheduleHad scheduleHad) {
		this.scheduleHad = scheduleHad;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
