package com.future.bbetter.schedule.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ScheduleHad.java auto generated by Charles. 2017/9/3 下午 05:39:31
 */
@Entity
@Table(name = "schedule_had")
public class ScheduleHad {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	@Column(name = "schedule_had_id")
	private Long scheduleHadId;
	@Column(name = "schedule_id")
	private Long scheduleId;
	@Column(name = "member_id")
	private Long memberId;
	@Column(name = "authority")
	private Integer authority;
	@Column(name = "is_valid")
	private Integer isValid;
	@Column(name = "accumulated_time")
	private Integer accumulatedTime;

	public ScheduleHad(){}
	public ScheduleHad(Long scheduleHadId){
		this.scheduleHadId = scheduleHadId;
	}

	public void setScheduleHadId(Long scheduleHadId){
		this.scheduleHadId = scheduleHadId;
	}
	public Long getScheduleHadId() {
			return this.scheduleHadId;
	}
	public void setScheduleId(Long scheduleId){
		this.scheduleId = scheduleId;
	}
	public Long getScheduleId() {
			return this.scheduleId;
	}
	public void setMemberId(Long memberId){
		this.memberId = memberId;
	}
	public Long getMemberId() {
			return this.memberId;
	}
	public void setAuthority(Integer authority){
		this.authority = authority;
	}
	public Integer getAuthority() {
			return this.authority;
	}
	public void setIsValid(Integer isValid){
		this.isValid = isValid;
	}
	public Integer getIsValid() {
			return this.isValid;
	}
	public void setAccumulatedTime(Integer accumulatedTime){
		this.accumulatedTime = accumulatedTime;
	}
	public Integer getAccumulatedTime() {
			return this.accumulatedTime;
	}


	@Override
	public String toString() {
		return String.format(
				"ScheduleHad [scheduleHadId=%s, scheduleId=%s, memberId=%s, authority=%s, isValid=%s, accumulatedTime=%s]",scheduleHadId, scheduleId, memberId, authority, isValid, accumulatedTime);
	}
}
