package com.future.bbetter.schedule.model;
// Generated 2017/9/24 下午 02:49:40 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "schedule", catalog = "bbetter")
public class Schedule implements java.io.Serializable {

	private Long scheduleId;
	private ScheduleSubType scheduleSubType;
	private Date startTime;
	private Date endTime;
	private String name;
	private String location;
	private int status;
	private Integer continuousTime;
	private int visibility;
	private int isCycle;
	private int isNeedRemind;
	private int isTeamSchedule;
	private int isValid;
	private Date createdate;
	private Date updatedate;
	private Set<ReportSchedule> reportSchedules = new HashSet<ReportSchedule>(0);
	private Set<ScheduleHad> scheduleHads = new HashSet<ScheduleHad>(0);

	public Schedule() {
	}

	public Schedule(ScheduleSubType scheduleSubType, Date startTime, String name, int status, int visibility,
			int isCycle, int isNeedRemind, int isTeamSchedule, int isValid, Date createdate) {
		this.scheduleSubType = scheduleSubType;
		this.startTime = startTime;
		this.name = name;
		this.status = status;
		this.visibility = visibility;
		this.isCycle = isCycle;
		this.isNeedRemind = isNeedRemind;
		this.isTeamSchedule = isTeamSchedule;
		this.isValid = isValid;
		this.createdate = createdate;
	}

	public Schedule(ScheduleSubType scheduleSubType, Date startTime, Date endTime, String name, String location,
			int status, Integer continuousTime, int visibility, int isCycle, int isNeedRemind, int isTeamSchedule,
			int isValid, Date createdate, Date updatedate, Set<ReportSchedule> reportSchedules,
			Set<ScheduleHad> scheduleHads) {
		this.scheduleSubType = scheduleSubType;
		this.startTime = startTime;
		this.endTime = endTime;
		this.name = name;
		this.location = location;
		this.status = status;
		this.continuousTime = continuousTime;
		this.visibility = visibility;
		this.isCycle = isCycle;
		this.isNeedRemind = isNeedRemind;
		this.isTeamSchedule = isTeamSchedule;
		this.isValid = isValid;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.reportSchedules = reportSchedules;
		this.scheduleHads = scheduleHads;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "schedule_id", unique = true, nullable = false)
	public Long getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Long scheduleId) {
		this.scheduleId = scheduleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schedule_sub_type_id", nullable = false)
	public ScheduleSubType getScheduleSubType() {
		return this.scheduleSubType;
	}

	public void setScheduleSubType(ScheduleSubType scheduleSubType) {
		this.scheduleSubType = scheduleSubType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", nullable = false, length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "location", length = 100)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "continuous_time")
	public Integer getContinuousTime() {
		return this.continuousTime;
	}

	public void setContinuousTime(Integer continuousTime) {
		this.continuousTime = continuousTime;
	}

	@Column(name = "visibility", nullable = false)
	public int getVisibility() {
		return this.visibility;
	}

	public void setVisibility(int visibility) {
		this.visibility = visibility;
	}

	@Column(name = "is_cycle", nullable = false)
	public int getIsCycle() {
		return this.isCycle;
	}

	public void setIsCycle(int isCycle) {
		this.isCycle = isCycle;
	}

	@Column(name = "is_need_remind", nullable = false)
	public int getIsNeedRemind() {
		return this.isNeedRemind;
	}

	public void setIsNeedRemind(int isNeedRemind) {
		this.isNeedRemind = isNeedRemind;
	}

	@Column(name = "is_team_schedule", nullable = false)
	public int getIsTeamSchedule() {
		return this.isTeamSchedule;
	}

	public void setIsTeamSchedule(int isTeamSchedule) {
		this.isTeamSchedule = isTeamSchedule;
	}

	@Column(name = "is_valid", nullable = false)
	public int getIsValid() {
		return this.isValid;
	}

	public void setIsValid(int isValid) {
		this.isValid = isValid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedate", length = 19)
	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
	public Set<ReportSchedule> getReportSchedules() {
		return this.reportSchedules;
	}

	public void setReportSchedules(Set<ReportSchedule> reportSchedules) {
		this.reportSchedules = reportSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
	public Set<ScheduleHad> getScheduleHads() {
		return this.scheduleHads;
	}

	public void setScheduleHads(Set<ScheduleHad> scheduleHads) {
		this.scheduleHads = scheduleHads;
	}

}
