package com.future.bbetter.schedule.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Schedule.java auto generated by Charles. 2017/9/3 下午 05:39:31
 */
@Entity
@Table(name = "schedule")
public class Schedule {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	@Column(name = "schedule_id")
	private Long scheduleId;
	@Column(name = "schedule_sub_type_id")
	private Integer scheduleSubTypeId;
	@Column(name = "start_time")
	private Date startTime;
	@Column(name = "end_time")
	private Date endTime;
	@Column(name = "name")
	private String name;
	@Column(name = "location")
	private String location;
	@Column(name = "status")
	private Integer status;
	@Column(name = "continuous_time")
	private Integer continuousTime;
	@Column(name = "visibility")
	private Integer visibility;
	@Column(name = "is_cycle")
	private Integer isCycle;
	@Column(name = "is_need_remind")
	private Integer isNeedRemind;
	@Column(name = "is_team_schedule")
	private Integer isTeamSchedule;
	@Column(name = "is_valid")
	private Integer isValid;
	@Column(name = "createdate")
	private Date createdate;
	@Column(name = "updatedate")
	private Date updatedate;

	public Schedule(){}
	public Schedule(Long scheduleId){
		this.scheduleId = scheduleId;
	}

	public void setScheduleId(Long scheduleId){
		this.scheduleId = scheduleId;
	}
	public Long getScheduleId() {
			return this.scheduleId;
	}
	public void setScheduleSubTypeId(Integer scheduleSubTypeId){
		this.scheduleSubTypeId = scheduleSubTypeId;
	}
	public Integer getScheduleSubTypeId() {
			return this.scheduleSubTypeId;
	}
	public void setStartTime(Date startTime){
		this.startTime = startTime;
	}
	public Date getStartTime() {
			return this.startTime;
	}
	public void setEndTime(Date endTime){
		this.endTime = endTime;
	}
	public Date getEndTime() {
			return this.endTime;
	}
	public void setName(String name){
		this.name = name;
	}
	public String getName() {
			return this.name;
	}
	public void setLocation(String location){
		this.location = location;
	}
	public String getLocation() {
			return this.location;
	}
	public void setStatus(Integer status){
		this.status = status;
	}
	public Integer getStatus() {
			return this.status;
	}
	public void setContinuousTime(Integer continuousTime){
		this.continuousTime = continuousTime;
	}
	public Integer getContinuousTime() {
			return this.continuousTime;
	}
	public void setVisibility(Integer visibility){
		this.visibility = visibility;
	}
	public Integer getVisibility() {
			return this.visibility;
	}
	public void setIsCycle(Integer isCycle){
		this.isCycle = isCycle;
	}
	public Integer getIsCycle() {
			return this.isCycle;
	}
	public void setIsNeedRemind(Integer isNeedRemind){
		this.isNeedRemind = isNeedRemind;
	}
	public Integer getIsNeedRemind() {
			return this.isNeedRemind;
	}
	public void setIsTeamSchedule(Integer isTeamSchedule){
		this.isTeamSchedule = isTeamSchedule;
	}
	public Integer getIsTeamSchedule() {
			return this.isTeamSchedule;
	}
	public void setIsValid(Integer isValid){
		this.isValid = isValid;
	}
	public Integer getIsValid() {
			return this.isValid;
	}
	public void setCreatedate(Date createdate){
		this.createdate = createdate;
	}
	public Date getCreatedate() {
			return this.createdate;
	}
	public void setUpdatedate(Date updatedate){
		this.updatedate = updatedate;
	}
	public Date getUpdatedate() {
			return this.updatedate;
	}


	@Override
	public String toString() {
		return String.format(
				"Schedule [scheduleId=%s, scheduleSubTypeId=%s, startTime=%s, endTime=%s, name=%s, location=%s, status=%s, continuousTime=%s, visibility=%s, isCycle=%s, isNeedRemind=%s, isTeamSchedule=%s, isValid=%s, createdate=%s, updatedate=%s]",scheduleId, scheduleSubTypeId, startTime, endTime, name, location, status, continuousTime, visibility, isCycle, isNeedRemind, isTeamSchedule, isValid, createdate, updatedate);
	}
}
