package com.future.bbetter.achievement.model;
// Generated 2017/9/24 下午 02:49:40 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AchievementType generated by hbm2java
 */
@Entity
@Table(name = "achievement_type", catalog = "bbetter")
public class AchievementType implements java.io.Serializable {

	private Integer achievementTypeId;
	private String name;
	private Set<AchievementHad> achievementHads = new HashSet<AchievementHad>(0);

	public AchievementType() {
	}

	public AchievementType(String name) {
		this.name = name;
	}

	public AchievementType(String name, Set<AchievementHad> achievementHads) {
		this.name = name;
		this.achievementHads = achievementHads;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "achievement_type_id", unique = true, nullable = false)
	public Integer getAchievementTypeId() {
		return this.achievementTypeId;
	}

	public void setAchievementTypeId(Integer achievementTypeId) {
		this.achievementTypeId = achievementTypeId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "achievementType")
	public Set<AchievementHad> getAchievementHads() {
		return this.achievementHads;
	}

	public void setAchievementHads(Set<AchievementHad> achievementHads) {
		this.achievementHads = achievementHads;
	}

}
