package com.future.bbetter.achievement.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AchievementType.java auto generated by Charles. 2017/9/3 下午 05:39:31
 */
@Entity
@Table(name = "achievement_type")
public class AchievementType {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	@Column(name = "achievement_type_id")
	private Integer achievementTypeId;
	@Column(name = "name")
	private String name;

	public AchievementType(){}
	public AchievementType(Integer achievementTypeId){
		this.achievementTypeId = achievementTypeId;
	}

	public void setAchievementTypeId(Integer achievementTypeId){
		this.achievementTypeId = achievementTypeId;
	}
	public Integer getAchievementTypeId() {
			return this.achievementTypeId;
	}
	public void setName(String name){
		this.name = name;
	}
	public String getName() {
			return this.name;
	}


	@Override
	public String toString() {
		return String.format(
				"AchievementType [achievementTypeId=%s, name=%s]",achievementTypeId, name);
	}
}
