package com.future.bbetter.achievement.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AchievementHad.java auto generated by Charles. 2017/9/3 下午 05:39:31
 */
@Entity
@Table(name = "achievement_had")
public class AchievementHad {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	@Column(name = "achievement_had_id")
	private Integer achievementHadId;
	@Column(name = "achievement_type_id")
	private Integer achievementTypeId;
	@Column(name = "member_id")
	private Long memberId;
	@Column(name = "getdate")
	private Date getdate;

	public AchievementHad(){}
	public AchievementHad(Integer achievementHadId){
		this.achievementHadId = achievementHadId;
	}

	public void setAchievementHadId(Integer achievementHadId){
		this.achievementHadId = achievementHadId;
	}
	public Integer getAchievementHadId() {
			return this.achievementHadId;
	}
	public void setAchievementTypeId(Integer achievementTypeId){
		this.achievementTypeId = achievementTypeId;
	}
	public Integer getAchievementTypeId() {
			return this.achievementTypeId;
	}
	public void setMemberId(Long memberId){
		this.memberId = memberId;
	}
	public Long getMemberId() {
			return this.memberId;
	}
	public void setGetdate(Date getdate){
		this.getdate = getdate;
	}
	public Date getGetdate() {
			return this.getdate;
	}


	@Override
	public String toString() {
		return String.format(
				"AchievementHad [achievementHadId=%s, achievementTypeId=%s, memberId=%s, getdate=%s]",achievementHadId, achievementTypeId, memberId, getdate);
	}
}
