package com.future.bbetter.achievement.model;
// Generated 2017/9/24 下午 02:49:40 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.future.bbetter.member.model.Member;

/**
 * AchievementHad generated by hbm2java
 */
@Entity
@Table(name = "achievement_had", catalog = "bbetter")
public class AchievementHad implements java.io.Serializable {

	private Integer achievementHadId;
	private AchievementType achievementType;
	private Member member;
	private Date getdate;

	public AchievementHad() {
	}

	public AchievementHad(AchievementType achievementType, Member member, Date getdate) {
		this.achievementType = achievementType;
		this.member = member;
		this.getdate = getdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "achievement_had_id", unique = true, nullable = false)
	public Integer getAchievementHadId() {
		return this.achievementHadId;
	}

	public void setAchievementHadId(Integer achievementHadId) {
		this.achievementHadId = achievementHadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "achievement_type_id", nullable = false)
	public AchievementType getAchievementType() {
		return this.achievementType;
	}

	public void setAchievementType(AchievementType achievementType) {
		this.achievementType = achievementType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "getdate", nullable = false, length = 19)
	public Date getGetdate() {
		return this.getdate;
	}

	public void setGetdate(Date getdate) {
		this.getdate = getdate;
	}

}
