package com.future.bbetter.pet.model;
// Generated 2017/9/24 下午 02:49:40 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pet generated by hbm2java
 */
@Entity
@Table(name = "pet", catalog = "bbetter")
public class Pet implements java.io.Serializable {

	private Integer petId;
	private String name;
	private int initHeight;
	private int initWeight;
	private int initVision;
	private int initHp;
	private int initMp;
	private int initMentality;
	private int initStrength;
	private int initIntelligence;
	private int initDexterity;
	private int initVitality;
	private Set<PetsHad> petsHads = new HashSet<PetsHad>(0);

	public Pet() {
	}

	public Pet(String name, int initHeight, int initWeight, int initVision, int initHp, int initMp, int initMentality,
			int initStrength, int initIntelligence, int initDexterity, int initVitality) {
		this.name = name;
		this.initHeight = initHeight;
		this.initWeight = initWeight;
		this.initVision = initVision;
		this.initHp = initHp;
		this.initMp = initMp;
		this.initMentality = initMentality;
		this.initStrength = initStrength;
		this.initIntelligence = initIntelligence;
		this.initDexterity = initDexterity;
		this.initVitality = initVitality;
	}

	public Pet(String name, int initHeight, int initWeight, int initVision, int initHp, int initMp, int initMentality,
			int initStrength, int initIntelligence, int initDexterity, int initVitality, Set<PetsHad> petsHads) {
		this.name = name;
		this.initHeight = initHeight;
		this.initWeight = initWeight;
		this.initVision = initVision;
		this.initHp = initHp;
		this.initMp = initMp;
		this.initMentality = initMentality;
		this.initStrength = initStrength;
		this.initIntelligence = initIntelligence;
		this.initDexterity = initDexterity;
		this.initVitality = initVitality;
		this.petsHads = petsHads;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pet_id", unique = true, nullable = false)
	public Integer getPetId() {
		return this.petId;
	}

	public void setPetId(Integer petId) {
		this.petId = petId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "init_height", nullable = false)
	public int getInitHeight() {
		return this.initHeight;
	}

	public void setInitHeight(int initHeight) {
		this.initHeight = initHeight;
	}

	@Column(name = "init_weight", nullable = false)
	public int getInitWeight() {
		return this.initWeight;
	}

	public void setInitWeight(int initWeight) {
		this.initWeight = initWeight;
	}

	@Column(name = "init_vision", nullable = false)
	public int getInitVision() {
		return this.initVision;
	}

	public void setInitVision(int initVision) {
		this.initVision = initVision;
	}

	@Column(name = "init_hp", nullable = false)
	public int getInitHp() {
		return this.initHp;
	}

	public void setInitHp(int initHp) {
		this.initHp = initHp;
	}

	@Column(name = "init_mp", nullable = false)
	public int getInitMp() {
		return this.initMp;
	}

	public void setInitMp(int initMp) {
		this.initMp = initMp;
	}

	@Column(name = "init_mentality", nullable = false)
	public int getInitMentality() {
		return this.initMentality;
	}

	public void setInitMentality(int initMentality) {
		this.initMentality = initMentality;
	}

	@Column(name = "init_strength", nullable = false)
	public int getInitStrength() {
		return this.initStrength;
	}

	public void setInitStrength(int initStrength) {
		this.initStrength = initStrength;
	}

	@Column(name = "init_intelligence", nullable = false)
	public int getInitIntelligence() {
		return this.initIntelligence;
	}

	public void setInitIntelligence(int initIntelligence) {
		this.initIntelligence = initIntelligence;
	}

	@Column(name = "init_dexterity", nullable = false)
	public int getInitDexterity() {
		return this.initDexterity;
	}

	public void setInitDexterity(int initDexterity) {
		this.initDexterity = initDexterity;
	}

	@Column(name = "init_vitality", nullable = false)
	public int getInitVitality() {
		return this.initVitality;
	}

	public void setInitVitality(int initVitality) {
		this.initVitality = initVitality;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pet")
	public Set<PetsHad> getPetsHads() {
		return this.petsHads;
	}

	public void setPetsHads(Set<PetsHad> petsHads) {
		this.petsHads = petsHads;
	}

}
