package com.future.bbetter.pet.model;
// Generated 2017/9/24 下午 02:49:40 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.future.bbetter.member.model.Member;

/**
 * PetsHad generated by hbm2java
 */
@Entity
@Table(name = "pets_had", catalog = "bbetter")
public class PetsHad implements java.io.Serializable {

	private Integer petsHadId;
	private Member member;
	private Pet pet;
	private String nickname;
	private int isCurrent;
	private int height;
	private int weight;
	private int vision;
	private int hp;
	private int mp;
	private int mentality;
	private int strength;
	private int intelligence;
	private int dexterity;
	private int vitality;
	private int isDeath;

	public PetsHad() {
	}

	public PetsHad(Member member, Pet pet, int isCurrent, int height, int weight, int vision, int hp, int mp,
			int mentality, int strength, int intelligence, int dexterity, int vitality, int isDeath) {
		this.member = member;
		this.pet = pet;
		this.isCurrent = isCurrent;
		this.height = height;
		this.weight = weight;
		this.vision = vision;
		this.hp = hp;
		this.mp = mp;
		this.mentality = mentality;
		this.strength = strength;
		this.intelligence = intelligence;
		this.dexterity = dexterity;
		this.vitality = vitality;
		this.isDeath = isDeath;
	}

	public PetsHad(Member member, Pet pet, String nickname, int isCurrent, int height, int weight, int vision, int hp,
			int mp, int mentality, int strength, int intelligence, int dexterity, int vitality, int isDeath) {
		this.member = member;
		this.pet = pet;
		this.nickname = nickname;
		this.isCurrent = isCurrent;
		this.height = height;
		this.weight = weight;
		this.vision = vision;
		this.hp = hp;
		this.mp = mp;
		this.mentality = mentality;
		this.strength = strength;
		this.intelligence = intelligence;
		this.dexterity = dexterity;
		this.vitality = vitality;
		this.isDeath = isDeath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pets_had_id", unique = true, nullable = false)
	public Integer getPetsHadId() {
		return this.petsHadId;
	}

	public void setPetsHadId(Integer petsHadId) {
		this.petsHadId = petsHadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pet_id", nullable = false)
	public Pet getPet() {
		return this.pet;
	}

	public void setPet(Pet pet) {
		this.pet = pet;
	}

	@Column(name = "nickname", length = 60)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "is_current", nullable = false)
	public int getIsCurrent() {
		return this.isCurrent;
	}

	public void setIsCurrent(int isCurrent) {
		this.isCurrent = isCurrent;
	}

	@Column(name = "height", nullable = false)
	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	@Column(name = "weight", nullable = false)
	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	@Column(name = "vision", nullable = false)
	public int getVision() {
		return this.vision;
	}

	public void setVision(int vision) {
		this.vision = vision;
	}

	@Column(name = "hp", nullable = false)
	public int getHp() {
		return this.hp;
	}

	public void setHp(int hp) {
		this.hp = hp;
	}

	@Column(name = "mp", nullable = false)
	public int getMp() {
		return this.mp;
	}

	public void setMp(int mp) {
		this.mp = mp;
	}

	@Column(name = "mentality", nullable = false)
	public int getMentality() {
		return this.mentality;
	}

	public void setMentality(int mentality) {
		this.mentality = mentality;
	}

	@Column(name = "strength", nullable = false)
	public int getStrength() {
		return this.strength;
	}

	public void setStrength(int strength) {
		this.strength = strength;
	}

	@Column(name = "intelligence", nullable = false)
	public int getIntelligence() {
		return this.intelligence;
	}

	public void setIntelligence(int intelligence) {
		this.intelligence = intelligence;
	}

	@Column(name = "dexterity", nullable = false)
	public int getDexterity() {
		return this.dexterity;
	}

	public void setDexterity(int dexterity) {
		this.dexterity = dexterity;
	}

	@Column(name = "vitality", nullable = false)
	public int getVitality() {
		return this.vitality;
	}

	public void setVitality(int vitality) {
		this.vitality = vitality;
	}

	@Column(name = "is_death", nullable = false)
	public int getIsDeath() {
		return this.isDeath;
	}

	public void setIsDeath(int isDeath) {
		this.isDeath = isDeath;
	}

}
